### ISSUE TITLE
MODx 2.3+ compactibility?

### ISSUE THREAD

**Issue by rustedwolf** [jgulledge19/Slideshowmanager#23]
ATM it says "Compatible up to Revolution 2.2.x". Therefore it's not available in 2.3's repository list.
Will there be an update?

**Comment by jgulledge19** [comment]
Yes it should work in 2.3 but I need to post fixes for the UI. Some of the boxes are to wide or narrow.

**Comment by jgulledge19** [comment]
You should now be able to install via your Package Manager: http://modx.com/extras/package/slideshowmanager
